name: Release

on:
  push:
    branches:
      - release

jobs:

  skip:
    name: Maybe skip?
    runs-on: ubuntu-20.04
    outputs:
      skip: ${{ steps.skip.outputs.skip }}
    steps:
      - uses: actions/checkout@v2

      - name: Skip Output
        id: skip
        run: make ci/skip

  checks:
    name: Pre-release checks
    runs-on: ubuntu-20.04
    needs: skip
    if: ${{ needs.skip.outputs.skip == 'false' }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Check
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test

  changelog:
    name: Generate Changelog
    runs-on: ubuntu-20.04
    needs: checks
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - name: Configure Git
        run: |
          git config --global user.name "Viktor Kuroljov"
          git config --global user.email ${{ secrets.EMAIL }}

      - uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.SSH_KEY }}

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Setup Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12

      - name: Install Deps
        run: make ci/install

      - name: Build versioning tools
        run: make ci/build

      - name: Changelog
        id: changelog
        run: make ci/release

      - name: Push `release` branch
        run: git push origin release

      - name: Push new tag
        run: git push origin $(git describe --abbrev=0)

      - name: Tag Output
        id: tag
        run: echo "::set-output name=tag::$(git describe --abbrev=0)"

  github-release:
    name: Github Release
    runs-on: ubuntu-20.04
    needs: changelog
    steps:
      - name: Github Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.changelog.outputs.tag }}
          release_name: ${{ needs.changelog.outputs.tag }}

  sync:
    name: Sync master & release
    runs-on: ubuntu-latest
    needs: changelog
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: 0
          ssh-key: ${{ secrets.SSH_KEY }}

      - name: Sync
        run: make sync/master
